"use client";
import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Search } from "lucide-react";
import { cx } from "@/components/ui";
import { useReader } from "./context";

/** The original source, segment by segment, so the learner can verify the AI's interpretation. */
export function SourceView() {
  const { book, sourceFocus } = useReader();
  const [q, setQ] = useState("");
  const videoId = book.source.kind === "youtube" ? (book.source.meta?.videoId as string | undefined) : undefined;
  const focusSeg = sourceFocus ? book.segments.find((s) => s.idx === sourceFocus) : null;
  const [playerStart, setPlayerStart] = useState<number>(focusSeg?.start_sec ? Math.floor(Number(focusSeg.start_sec)) : 0);

  useEffect(() => {
    if (!sourceFocus) return;
    const seg = book.segments.find((s) => s.idx === sourceFocus);
    // eslint-disable-next-line react-hooks/set-state-in-effect -- sync player to the citation that was clicked
    if (seg?.start_sec != null) setPlayerStart(Math.floor(Number(seg.start_sec)));
    const t = setTimeout(() => {
      const el = document.getElementById(`seg-${sourceFocus}`);
      el?.scrollIntoView({ behavior: "smooth", block: "center" });
      el?.classList.add("flash-target");
      setTimeout(() => el?.classList.remove("flash-target"), 1700);
    }, 60);
    return () => clearTimeout(t);
  }, [sourceFocus, book.segments]);

  const filtered = useMemo(() => {
    const term = q.trim().toLowerCase();
    return term ? book.segments.filter((s) => s.text.toLowerCase().includes(term)) : book.segments;
  }, [q, book.segments]);

  const meta = book.source.meta ?? {};
  return (
    <div className="font-sans">
      <header>
        <p className="text-accent text-xs font-semibold tracking-[0.18em] uppercase">Original source</p>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight">{book.source.title}</h1>
        <p className="text-muted mt-1 flex flex-wrap items-center gap-2 text-sm">
          <span className="capitalize">{book.source.kind}</span>
          {typeof meta.author === "string" && <span>· {meta.author}</span>}
          {meta.autoGeneratedCaptions === true && <span>· auto-generated captions (may contain recognition errors)</span>}
          {book.source.url && (
            <a
              href={book.source.url}
              target="_blank"
              rel="noreferrer"
              className="text-accent inline-flex items-center gap-1 hover:underline"
            >
              Open original <ExternalLink className="size-3" />
            </a>
          )}
        </p>
      </header>

      {videoId && (
        <div className="border-line sticky top-2 z-10 mt-6 aspect-video w-full overflow-hidden rounded-2xl border bg-black shadow-lg">
          <iframe
            key={playerStart}
            src={`https://www.youtube-nocookie.com/embed/${videoId}?start=${playerStart}&autoplay=${sourceFocus ? 1 : 0}`}
            title={book.source.title ?? "Video"}
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; picture-in-picture"
            allowFullScreen
            className="size-full"
          />
        </div>
      )}

      <div className="relative mt-6">
        <Search className="text-muted absolute top-1/2 left-3 size-4 -translate-y-1/2" />
        <input
          value={q}
          onChange={(e) => setQ(e.target.value)}
          placeholder="Search the original source"
          aria-label="Search the original source"
          className="border-line bg-surface focus:border-accent h-10 w-full rounded-xl border pr-3 pl-9 text-sm outline-none"
        />
      </div>
      {q && <p className="text-muted mt-2 text-sm">{filtered.length} matching segments</p>}

      <ol className="mt-6 space-y-2">
        {filtered.map((s, i) => {
          const prev = filtered[i - 1];
          return (
            <li key={s.idx}>
              {s.heading && s.heading !== prev?.heading && <h2 className="mt-6 mb-2 font-semibold">{s.heading}</h2>}
              <div
                id={`seg-${s.idx}`}
                className={cx(
                  "grid scroll-mt-28 grid-cols-[5.5rem_1fr] gap-3 rounded-xl p-3 text-[0.95rem] leading-relaxed transition",
                  sourceFocus === s.idx ? "bg-accent-soft" : "hover:bg-surface-2",
                )}
              >
                <button
                  className={cx("text-muted h-fit text-left text-xs font-medium tabular-nums", s.start_sec != null && "hover:text-accent")}
                  onClick={() => s.start_sec != null && setPlayerStart(Math.floor(Number(s.start_sec)))}
                  disabled={s.start_sec == null}
                  title={s.start_sec != null ? "Play from here" : undefined}
                >
                  {s.ref_label}
                </button>
                <p className="text-ink-2 whitespace-pre-wrap">{s.text}</p>
              </div>
            </li>
          );
        })}
      </ol>
    </div>
  );
}
