import "server-only";
import { countWords, guessLanguage, normalizeWhitespace } from "./clean";
import { segmentsFromCues, segmentsFromPages, segmentsFromText, parseTimedTranscript, type Segment } from "./segment";
import { fetchYouTubeTitle, fetchYouTubeTranscript, parseYouTubeId, TranscriptUnavailableError } from "./youtube";
import type { SourceKind } from "@/lib/content/types";
import { assertPublicUrl } from "@/lib/server/net";

export class SourceError extends Error {
  constructor(
    message: string,
    readonly status = 422,
  ) {
    super(message);
    this.name = "SourceError";
  }
}

export const MAX_SOURCE_WORDS = 150_000;
export const MIN_SOURCE_WORDS = 60;

export interface ExtractedSource {
  kind: SourceKind;
  title: string;
  url: string | null;
  language: string;
  meta: Record<string, unknown>;
  segments: Segment[];
  wordCount: number;
}

function finalize(partial: Omit<ExtractedSource, "wordCount" | "language"> & { language?: string }): ExtractedSource {
  const segments = partial.segments.filter((s) => s.text.trim());
  segments.forEach((s, i) => (s.idx = i + 1));
  const wordCount = segments.reduce((n, s) => n + countWords(s.text), 0);
  if (wordCount < MIN_SOURCE_WORDS) {
    throw new SourceError(
      `We could only find ${wordCount} words of readable text in this source — not enough to build a learning book. If this is a scanned PDF, it needs OCR first.`,
    );
  }
  if (wordCount > MAX_SOURCE_WORDS) {
    throw new SourceError(
      `This source has about ${wordCount.toLocaleString()} words; the current limit is ${MAX_SOURCE_WORDS.toLocaleString()}. Split it into parts and create one book per part.`,
    );
  }
  const language = partial.language ?? guessLanguage(segments.map((s) => s.text).join(" "));
  return { ...partial, segments, wordCount, language };
}

export async function extractYouTube(url: string, transcriptOverride?: string): Promise<ExtractedSource> {
  const videoId = parseYouTubeId(url);
  if (!videoId) throw new SourceError("That doesn't look like a valid YouTube video link.");
  const canonical = `https://www.youtube.com/watch?v=${videoId}`;

  if (transcriptOverride?.trim()) {
    const title = (await fetchYouTubeTitle(videoId)) ?? `YouTube video ${videoId}`;
    const fromTranscript = extractTranscriptText(transcriptOverride, title);
    return { ...fromTranscript, kind: "youtube", url: canonical, meta: { ...fromTranscript.meta, videoId, manualTranscript: true } };
  }

  try {
    const t = await fetchYouTubeTranscript(videoId);
    return finalize({
      kind: "youtube",
      title: t.title,
      url: canonical,
      language: t.language.split("-")[0],
      meta: {
        videoId,
        author: t.author,
        durationSeconds: t.durationSeconds,
        captionLanguage: t.language,
        autoGeneratedCaptions: t.autoGenerated,
      },
      segments: segmentsFromCues(t.cues),
    });
  } catch (e) {
    if (e instanceof TranscriptUnavailableError) throw new SourceError(e.message);
    throw e;
  }
}

export function extractTranscriptText(text: string, title: string): ExtractedSource {
  const cues = parseTimedTranscript(text);
  if (cues) {
    return finalize({ kind: "transcript", title, url: null, meta: { timed: true }, segments: segmentsFromCues(cues) });
  }
  return finalize({ kind: "transcript", title, url: null, meta: { timed: false }, segments: segmentsFromText(text) });
}

export function extractPlainText(text: string, title: string, kind: "text" | "txt" | "md"): ExtractedSource {
  // A pasted/uploaded file that is actually a timed transcript keeps its timestamps.
  const cues = parseTimedTranscript(text);
  if (cues) {
    return finalize({ kind: "transcript", title, url: null, meta: { timed: true }, segments: segmentsFromCues(cues) });
  }
  return finalize({ kind, title, url: null, meta: {}, segments: segmentsFromText(text, { markdown: kind === "md" }) });
}

export async function extractPdf(bytes: Uint8Array, title: string): Promise<ExtractedSource> {
  const { extractText, getDocumentProxy } = await import("unpdf");
  let pages: string[];
  try {
    const pdf = await getDocumentProxy(bytes);
    const res = await extractText(pdf, { mergePages: false });
    pages = res.text as string[];
  } catch {
    throw new SourceError("This PDF couldn't be read. It may be encrypted or corrupted.");
  }
  return finalize({ kind: "pdf", title, url: null, meta: { pages: pages.length }, segments: segmentsFromPages(pages) });
}

export async function extractDocx(bytes: Uint8Array, title: string): Promise<ExtractedSource> {
  const mammoth = await import("mammoth");
  try {
    const { value } = await mammoth.extractRawText({ buffer: Buffer.from(bytes) });
    return finalize({ kind: "docx", title, url: null, meta: {}, segments: segmentsFromText(value) });
  } catch (e) {
    if (e instanceof SourceError) throw e;
    throw new SourceError("This Word document couldn't be read. Only .docx (not legacy .doc) is supported.");
  }
}

export async function extractArticle(url: string): Promise<ExtractedSource> {
  let parsed: URL;
  try {
    parsed = new URL(url);
    if (!/^https?:$/.test(parsed.protocol)) throw new Error();
  } catch {
    throw new SourceError("Please enter a valid http(s) article URL.");
  }
  try {
    await assertPublicUrl(parsed);
  } catch {
    throw new SourceError("That URL points to a private or unreachable address.");
  }
  let html: string;
  try {
    // Follow redirects manually so every hop is checked against private networks.
    let target = parsed;
    let res: Response | null = null;
    for (let hop = 0; hop < 5; hop++) {
      await assertPublicUrl(target);
      res = await fetch(target, {
        headers: { "User-Agent": "Mozilla/5.0 (compatible; AILearningStudio/1.0)", Accept: "text/html" },
        signal: AbortSignal.timeout(20_000),
        redirect: "manual",
      });
      const location = res.status >= 300 && res.status < 400 ? res.headers.get("location") : null;
      if (!location) break;
      target = new URL(location, target);
      res = null;
    }
    if (!res) throw new Error("too many redirects");
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    if (!(res.headers.get("content-type") ?? "").includes("html")) throw new Error("not an HTML page");
    html = await res.text();
  } catch (e) {
    throw new SourceError(`Couldn't download that article (${(e as Error).message}). Paste its text instead.`);
  }
  const [{ parseHTML }, { Readability }] = await Promise.all([import("linkedom"), import("@mozilla/readability")]);
  const { document } = parseHTML(html);
  const article = new Readability(document as unknown as Document).parse();
  if (!article?.textContent) throw new SourceError("Couldn't find the main article text on that page. Paste its text instead.");
  // Keep paragraph boundaries from the extracted HTML.
  const { document: contentDoc } = parseHTML(`<html><body>${article.content ?? ""}</body></html>`);
  const blocks = Array.from(contentDoc.querySelectorAll("h1,h2,h3,h4,p,li,blockquote,pre"))
    .map((el) => {
      const t = normalizeWhitespace(el.textContent ?? "");
      return /^H\d$/.test(el.tagName) && t ? `## ${t}` : t;
    })
    .filter(Boolean);
  const text = blocks.length ? blocks.join("\n\n") : article.textContent;
  return finalize({
    kind: "article",
    title: article.title || parsed.hostname,
    url: parsed.toString(),
    meta: { siteName: article.siteName ?? parsed.hostname, byline: article.byline ?? null },
    segments: segmentsFromText(text, { markdown: true }),
  });
}

export function kindFromFilename(name: string): SourceKind | null {
  const ext = name.toLowerCase().split(".").pop();
  switch (ext) {
    case "pdf":
      return "pdf";
    case "docx":
      return "docx";
    case "md":
    case "markdown":
      return "md";
    case "txt":
      return "txt";
    case "srt":
    case "vtt":
      return "transcript";
    default:
      return null;
  }
}
