import type { TimedCue } from "./segment";

export class TranscriptUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "TranscriptUnavailableError";
  }
}

const ID_RE = /^[A-Za-z0-9_-]{11}$/;

/** Accepts watch, youtu.be, shorts, embed, live and music URLs. */
export function parseYouTubeId(input: string): string | null {
  const raw = input.trim();
  if (ID_RE.test(raw)) return raw;
  let url: URL;
  try {
    url = new URL(raw.startsWith("http") ? raw : `https://${raw}`);
  } catch {
    return null;
  }
  const host = url.hostname.replace(/^www\.|^m\.|^music\./, "");
  if (host === "youtu.be") {
    const id = url.pathname.slice(1).split("/")[0];
    return ID_RE.test(id) ? id : null;
  }
  if (host === "youtube.com" || host === "youtube-nocookie.com") {
    const v = url.searchParams.get("v");
    if (v && ID_RE.test(v)) return v;
    const m = url.pathname.match(/^\/(?:shorts|embed|live|v)\/([A-Za-z0-9_-]{11})/);
    if (m) return m[1];
  }
  return null;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string; // "asr" for auto-generated
  name?: { simpleText?: string; runs?: { text: string }[] };
}

export interface YouTubeTranscript {
  videoId: string;
  title: string;
  author: string | null;
  durationSeconds: number | null;
  language: string;
  autoGenerated: boolean;
  cues: TimedCue[];
}

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";

// Client identity used for the innertube player call. Android client responses
// return caption URLs that do not require a browser proof-of-origin token.
const INNERTUBE_CONTEXT = {
  client: { clientName: "ANDROID", clientVersion: "20.10.38", androidSdkVersion: 34, hl: "en" },
};

async function fetchText(url: string, init?: RequestInit): Promise<string> {
  const res = await fetch(url, {
    ...init,
    headers: { "User-Agent": UA, "Accept-Language": "en-US,en;q=0.9", ...(init?.headers ?? {}) },
    signal: AbortSignal.timeout(20_000),
    cache: "no-store",
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${new URL(url).pathname}`);
  return res.text();
}

function extractJsonAfter(html: string, marker: string): unknown | null {
  const at = html.indexOf(marker);
  if (at === -1) return null;
  const start = html.indexOf("{", at);
  if (start === -1) return null;
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = start; i < html.length; i++) {
    const c = html[i];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') inStr = true;
    else if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

type PlayerResponse = {
  playabilityStatus?: { status?: string; reason?: string };
  videoDetails?: { title?: string; author?: string; lengthSeconds?: string };
  captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } };
};

function pickTrack(tracks: CaptionTrack[], preferred: string[]): CaptionTrack {
  const manual = tracks.filter((t) => t.kind !== "asr");
  for (const lang of preferred) {
    const m = manual.find((t) => t.languageCode.toLowerCase().startsWith(lang));
    if (m) return m;
  }
  if (manual.length) return manual[0];
  for (const lang of preferred) {
    const a = tracks.find((t) => t.languageCode.toLowerCase().startsWith(lang));
    if (a) return a;
  }
  return tracks[0];
}

const ENTITIES: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: " " };
export function decodeEntities(s: string): string {
  return s.replace(/&(#x[0-9a-f]+|#\d+|\w+);/gi, (m, e: string) => {
    if (e[0] === "#") {
      const code = e[1] === "x" || e[1] === "X" ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : m;
    }
    return ENTITIES[e.toLowerCase()] ?? m;
  });
}

/** Parses both legacy `<text start dur>` and srv3 `<p t d>` timedtext XML. */
export function parseTimedTextXml(xml: string): TimedCue[] {
  const cues: TimedCue[] = [];
  for (const m of xml.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/g)) {
    const start = Number(m[1].match(/start="([\d.]+)"/)?.[1] ?? NaN);
    const dur = Number(m[1].match(/dur="([\d.]+)"/)?.[1] ?? 0);
    if (Number.isFinite(start)) cues.push({ start, duration: dur, text: decodeEntities(decodeEntities(m[2])) });
  }
  if (cues.length) return cues;
  for (const m of xml.matchAll(/<p\b([^>]*)>([\s\S]*?)<\/p>/g)) {
    const t = Number(m[1].match(/\bt="(\d+)"/)?.[1] ?? NaN);
    const d = Number(m[1].match(/\bd="(\d+)"/)?.[1] ?? 0);
    const text = decodeEntities(m[2].replace(/<[^>]+>/g, ""));
    if (Number.isFinite(t) && text.trim()) cues.push({ start: t / 1000, duration: d / 1000, text });
  }
  return cues;
}

async function playerViaInnertube(videoId: string, apiKey: string | null): Promise<PlayerResponse | null> {
  const url = `https://www.youtube.com/youtubei/v1/player${apiKey ? `?key=${apiKey}` : ""}`;
  try {
    const body = await fetchText(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ context: INNERTUBE_CONTEXT, videoId }),
    });
    return JSON.parse(body) as PlayerResponse;
  } catch {
    return null;
  }
}

export async function fetchYouTubeTranscript(videoId: string, preferredLanguages: string[] = ["en", "hi"]): Promise<YouTubeTranscript> {
  let html = "";
  try {
    html = await fetchText(`https://www.youtube.com/watch?v=${videoId}&hl=en`);
  } catch (e) {
    throw new TranscriptUnavailableError(
      `Could not reach YouTube to read this video (${(e as Error).message}). Paste the transcript instead.`,
    );
  }
  if (html.includes('action="https://consent.youtube.com')) {
    // EU consent interstitial: retry with a consent cookie.
    html = await fetchText(`https://www.youtube.com/watch?v=${videoId}&hl=en`, {
      headers: { Cookie: "CONSENT=YES+cb" },
    }).catch(() => html);
  }

  const apiKey = html.match(/"INNERTUBE_API_KEY":\s*"([^"]+)"/)?.[1] ?? null;
  const pagePlayer = extractJsonAfter(html, "ytInitialPlayerResponse") as PlayerResponse | null;
  const apiPlayer = await playerViaInnertube(videoId, apiKey);

  const details = pagePlayer?.videoDetails ?? apiPlayer?.videoDetails;
  const status = pagePlayer?.playabilityStatus ?? apiPlayer?.playabilityStatus;
  if (status?.status && status.status !== "OK" && !details) {
    throw new TranscriptUnavailableError(
      `YouTube says this video is unavailable${status.reason ? `: ${status.reason}` : ""}. Private, age-restricted or removed videos can't be analysed — paste the transcript instead.`,
    );
  }

  // Try tracks from the innertube response first (no PO token), then the page.
  const candidates = [
    apiPlayer?.captions?.playerCaptionsTracklistRenderer?.captionTracks,
    pagePlayer?.captions?.playerCaptionsTracklistRenderer?.captionTracks,
  ].filter((t): t is CaptionTrack[] => Array.isArray(t) && t.length > 0);

  if (!candidates.length) {
    throw new TranscriptUnavailableError(
      "This video has no captions/transcript available, so it cannot be analysed without guessing. Paste or upload a transcript instead.",
    );
  }

  for (const tracks of candidates) {
    const track = pickTrack(tracks, preferredLanguages);
    const base = track.baseUrl.replace(/&fmt=[^&]*/, "");
    try {
      const xml = await fetchText(base);
      const cues = parseTimedTextXml(xml);
      if (cues.length) {
        return {
          videoId,
          title: details?.title ?? `YouTube video ${videoId}`,
          author: details?.author ?? null,
          durationSeconds: details?.lengthSeconds ? Number(details.lengthSeconds) : null,
          language: track.languageCode,
          autoGenerated: track.kind === "asr",
          cues,
        };
      }
    } catch {
      // try next candidate list
    }
  }

  throw new TranscriptUnavailableError(
    "The video lists captions but YouTube refused to return them to our server (this happens with some regions and bot checks). Paste the transcript (YouTube → ··· → Show transcript) instead.",
  );
}

/** Title lookup that works even when captions don't (used for pasted transcripts). */
export async function fetchYouTubeTitle(videoId: string): Promise<string | null> {
  try {
    const res = await fetch(
      `https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${videoId}`)}`,
      { signal: AbortSignal.timeout(8000) },
    );
    if (!res.ok) return null;
    const data = (await res.json()) as { title?: string };
    return data.title ?? null;
  } catch {
    return null;
  }
}
